Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -111,33 +111,33 @@ jobs:
       # Docker image here that supports AWS CLI
     #steps:
       # Checkout code from git
-      - run:
-          name: Ensure back-end infrastructure exists
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/backend.yml \
+      #- run:
+          #name: Ensure back-end infrastructure exists
+          #command: |
+            #aws cloudformation deploy \
+              #--template-file .circleci/files/backend.yml \
               #--tags project=your-tag \
               # --stack-name "your back-end stack name with workflow id" \
               # --parameter-overrides ID="your workflow id"  
-              exit 1
-      - run:
-          name: Ensure front-end infrastructure exist
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/frontend.yml \
+              #exit 1
+      #- run:
+          #name: Ensure front-end infrastructure exist
+          #command: |
+            #aws cloudformation deploy \
+            #  --template-file .circleci/files/frontend.yml \
               #--tags project=your-tag \
               # --stack-name "your front-end stack name with workflow id" \
               # --parameter-overrides ID="your workflow id"  
-              exit 1
-      - run:
-          name: Add back-end ip to ansible inventory
-          command: |
+              #exit 1
+      #- run:
+          #name: Add back-end ip to ansible inventory
+          #command: |
             # Your code here
-            exit 1
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/.circleci/ansible/inventory.txt
+            #exit 1
+      #- persist_to_workspace:
+          #root: ~/
+          #paths:
+            #- project/.circleci/ansible/inventory.txt
       # Here's where you will add some code to rollback on failure      
 
   #configure-infrastructure:
@@ -147,16 +147,16 @@ jobs:
       # Checkout code from git
       # Add ssh keys with fingerprint
       # attach workspace
-      - run:
-          name: Install dependencies
-          command: |
+      #- run:
+          #name: Install dependencies
+          #command: |
             # Your code here
-            exit 1
-      - run:
-          name: Configure server
-          command: |
+            #exit 1
+      #- run:
+          #name: Configure server
+          #command: |
             # Your code here
-            exit 1
+            #exit 1
       # Here's where you will add some code to rollback on failure      
 
   #run-migrations:
@@ -164,16 +164,16 @@ jobs:
       # Docker image here that supports NodeJS
     #steps:
       # Checkout code from git
-      - run:
-          name: Run migrations
-          command: |
+      #- run:
+          #name: Run migrations
+          #command: |
             # Your code here
-            exit 1
-      - run:
-          name: Send migration results to memstash
-          command: |
+            #exit 1
+      #- run:
+          #name: Send migration results to memstash
+          #command: |
             # Your code here
-            exit 1
+            #exit 1
      # Here's where you will add some code to rollback on failure      
 
   #deploy-frontend:
@@ -181,19 +181,19 @@ jobs:
       # Docker image here that supports AWS CLI
     #steps:
       # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
+      #- run:
+          #name: Install dependencies
+          #command: |
             # your code here
-      - run:
-          name: Get backend url
-          command: |
+      #- run:
+          #name: Get backend url
+          #command: |
             # your code here
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-      - run:
-          name: Deploy frontend objects
-          command: |
+            #export API_URL="http://${BACKEND_IP}:3030"
+            #echo "${API_URL}"
+      #- run:
+          #name: Deploy frontend objects
+          #command: |
             # your code here
       # Here's where you will add some code to rollback on failure      
                     
@@ -204,13 +204,13 @@ jobs:
       # Checkout code from git
       # Add ssh keys with fingerprint
       # attach workspace
-      - run:
-          name: Install dependencies
-          command: |
+      #- run:
+          #name: Install dependencies
+          #command: |
             # your code here
-      - run:
-          name: Deploy backend
-          command: |
+      #- run:
+          #name: Deploy backend
+          #command: |
             # your code here
       # Here's where you will add some code to rollback on failure  
 
@@ -219,21 +219,21 @@ jobs:
       # Lightweight Docker image 
     #steps:
       # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
+      #- run:
+          #name: Install dependencies
+          #command: |
             # your code here
-      - run:
-          name: Get backend url
-          command: |
+      #- run:
+          #name: Get backend url
+          #command: |
             # your code here
-      - run:
-          name: Backend smoke test.
-          command: |
+      #- run:
+          #name: Backend smoke test.
+          #command: |
             # your code here
-      - run:
-          name: Frontend smoke test.
-          command: |
+      #- run:
+          #name: Frontend smoke test.
+          #command: |
             # your code here
       # Here's where you will add some code to rollback on failure  
 
@@ -242,34 +242,34 @@ jobs:
       # Docker image here that supports AWS CLI
     #steps:
       # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
+      #- run:
+          #name: Install dependencies
+          #command: |
             # your code here
-      - run:
-          name: Update cloudfront distribution
-          command: |
+      #- run:
+          #name: Update cloudfront distribution
+          #command: |
             # your code here
       # Here's where you will add some code to rollback on failure  
 
-cleanup:
-    docker:
+#cleanup:
+    #docker:
       # Docker image here
-    steps:
+    #steps:
       # Checkout code from git
-      - run:
-          name: Get old stack workflow id
-          command: |
+      #- run:
+          #name: Get old stack workflow id
+          #command: |
             # your code here
-            export OldWorkflowID="the id here"
-            export STACKS=[] #put the list of stacks here
-      - run:
-          name: Remove old stacks and files
-          command: |
-            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-            then
+            #export OldWorkflowID="the id here"
+            #export STACKS=[] #put the list of stacks here
+      #- run:
+          #name: Remove old stacks and files
+          #command: |
+            #if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            #then
               # your code here
-            fi
+            #fi
             
 
 workflows:
